exclude: ^\.pre-commit-config\.yaml$

priorities:
  checks: 0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        priority: checks
      - id: check-yaml
        priority: checks
      - id: check-toml
        priority: checks
      - id: check-xml
        priority: checks
      - id: detect-private-key
        priority: checks
      - id: check-case-conflict
        priority: checks
      - id: check-merge-conflict
        priority: checks
      - id: check-symlinks
        priority: checks
